  
  github: tommytestertwo
  twitter:
  about: "Testin' course websites since 2014."


JULIIRA:
    name: Julissa Lira
    prof: false
    gravatar: 
    website: "https://en.wikipedia.org/wiki/Korn"
    github: JULIIRA
    twitter: 
    about: "I'm just a second-year doing their best to get their master's"


